name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! After filing the bug report, we will look at your report as soon as possible! We will keep you up-to-date on the progress of resolving the bug!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: What browsers are you seeing the problem on? 
      options:
        - Google Chrome
        - Firefox
        - Safari (MacOs)
        - Safari (ios)
        - Microsoft Edge
        - Other browser (please specify)
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running? You can find the version settings under the general settings!
      options:
        - DEV-0.0.0 (Latest)
    validations:
      required: true
  - type: textarea
    id: other-info
    attributes:
      label: Other info
      description: Is there somethign else you want to tell us? Or maybe share a photo of the issue?
    validations:
      required: false
