blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/SyncBoxNL/SyncBox/discussions
    about: Ask your questions in our community!
  - name: Official Support
    url: mailto:info@syncbox.nl
    about: We can help you via mail too!
  - name: Security Vurnabilities
    url: mailto:info@syncbox.nl
    about: Please report security vulnerabilities by sending us a mail.
